# 1. Les tableaux Numpy

## 1.1 Créer un ndarray

### 1.1.1. Créer un ndarray à partir de listes

In [2]:
import numpy as np

notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10])

print(notre_tableau)
type(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10]


numpy.ndarray

In [3]:
mon_array_bidimensionnel = np.array( [ [1,2,3],[4,5,6],[7,8,9] ] )
print(mon_array_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# pour sélectionner la valeur de la troisième colonne première ligne

print(mon_array_bidimensionnel[0][2])
print(mon_array_bidimensionnel[0,2])

# pour sélectionner la première ligne

print(mon_array_bidimensionnel[:,0])

# pour sélectionner la première colonne

print(mon_array_bidimensionnel[0,:])

3
3
[1 4 7]
[1 2 3]


### Il s'agit d'un tableau d'entiers, on ne peut pas changer une valeur par un string par exemple

In [5]:
mon_array_bidimensionnel[0,0]="texte"

ValueError: invalid literal for int() with base 10: 'texte'

In [17]:
# attribut dtype : type de données dans l'array

mon_array_bidimensionnel.dtype

dtype('int32')

In [18]:
mon_array_bidimensionnel = np.array([[1,2,3],[4,5,6]], dtype = float)
print(mon_array_bidimensionnel)
mon_array_bidimensionnel.dtype

[[1. 2. 3.]
 [4. 5. 6.]]


dtype('float64')

### 1.1.2. Créer un ndarray grâce à des fonctions NumPy

In [19]:
# np.zeros() permet de créer un ndarray dont l'ensemble des éléments correspondent à la valeur 0.mon_array_bidimensionnel

array_zeros = np.zeros((4,6))
print(array_zeros)

# on peut spécifier le type aussi

array_zeros = np.zeros((4,6), dtype = int)
print(array_zeros)

# Si on veut seulement des uns, on utilise la fonction ones

array_ones = np.ones((4,6), dtype = int)
print(array_ones)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [24]:
# np.random/random() permet de réer un ndarray dont les valeurs des éléments sont aléatoires entre 0 et 1

array_random = np.random.random((4,2))
print(array_random)

[[0.59920881 0.36915288]
 [0.53925824 0.67163294]
 [0.75536897 0.97031014]
 [0.53985    0.65839206]]


### Fichier iris.csv

In [7]:
# Charger les données d'un fichier txt ou csv

iris = np.genfromtxt("jeux_de_donnees/iris.csv", delimiter = ";", skip_header = True)
print(iris)
print(iris.dtype)
type(iris)

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

numpy.ndarray

In [31]:
# Sauvegarder les données dans un fichier txt ou csv

np.savetxt("jeux_de_donnees/iris_2.csv", iris, delimiter = ";")

## 1.2. Indexation

### 1.2.1. Indexation simple

In [32]:
iris[2,1]

3.2

In [37]:
# Modifier la valeur à la troisième ligne, deuxième colonne

iris[2,1] = 4
iris[2,1]

4.0

### 1.2.2. Indexation booléenne

Pour sélectionner une portion de tableau on peut utiliser des masques booléens. == != < > <= >=

In [39]:
# On souhaite garder les valeurs supérieures à 2, peu importe la colonne

iris[iris>2] # On se retrouver avec un tableau unidimmensionnel

array([5.1, 3.5, 4.9, 3. , 4.7, 4. , 4.6, 3.1, 5. , 3.6, 5.4, 3.9, 4.6,
       3.4, 5. , 3.4, 4.4, 2.9, 4.9, 3.1, 5.4, 3.7, 4.8, 3.4, 4.8, 3. ,
       4.3, 3. , 5.8, 4. , 5.7, 4.4, 5.4, 3.9, 5.1, 3.5, 5.7, 3.8, 5.1,
       3.8, 5.4, 3.4, 5.1, 3.7, 4.6, 3.6, 5.1, 3.3, 4.8, 3.4, 5. , 3. ,
       5. , 3.4, 5.2, 3.5, 5.2, 3.4, 4.7, 3.2, 4.8, 3.1, 5.4, 3.4, 5.2,
       4.1, 5.5, 4.2, 4.9, 3.1, 5. , 3.2, 5.5, 3.5, 4.9, 3.6, 4.4, 3. ,
       5.1, 3.4, 5. , 3.5, 4.5, 2.3, 4.4, 3.2, 5. , 3.5, 5.1, 3.8, 4.8,
       3. , 5.1, 3.8, 4.6, 3.2, 5.3, 3.7, 5. , 3.3, 7. , 3.2, 4.7, 6.4,
       3.2, 4.5, 6.9, 3.1, 4.9, 5.5, 2.3, 4. , 6.5, 2.8, 4.6, 5.7, 2.8,
       4.5, 6.3, 3.3, 4.7, 4.9, 2.4, 3.3, 6.6, 2.9, 4.6, 5.2, 2.7, 3.9,
       5. , 3.5, 5.9, 3. , 4.2, 6. , 2.2, 4. , 6.1, 2.9, 4.7, 5.6, 2.9,
       3.6, 6.7, 3.1, 4.4, 5.6, 3. , 4.5, 5.8, 2.7, 4.1, 6.2, 2.2, 4.5,
       5.6, 2.5, 3.9, 5.9, 3.2, 4.8, 6.1, 2.8, 4. , 6.3, 2.5, 4.9, 6.1,
       2.8, 4.7, 6.4, 2.9, 4.3, 6.6, 3. , 4.4, 6.8, 2.8, 4.8, 6.

In [40]:
iris[iris>2].shape[0] # Nombre d'éléments supérieurs à 0

472

In [41]:
# L'expression booléenne qui suit génère un nouveau tableau, de même dimension que le tableau iris, mais qui contient uniquement des bool

iris>2

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, Fal

In [43]:
# Pour appliquer une condition sur une colonne particulère du tableau, il faut sélectionner en écrivant le masque booléen comme ceci :

iris[iris[:,0]>5] # On conserve la ligne si la première colonne est >5

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4.2, 1.4, 0.2, 1. ],
       [5.5, 3.5, 1.3, 0.2, 1. ],
       [5.1, 3.4, 1.5, 0.2, 1. ],
       [5.1, 3.8, 1.9, 0.4, 1. ],
       [5.1, 3.8, 1.6, 0.2, 1. ],
       [5.3, 3.7, 1.5, 0.2, 1. ],
       [7. , 3.2, 4.7, 1.4, 2. ],
       [6.4, 3.2, 4.5, 1.5, 2. ],
       [6.9, 3.1, 4.9, 1.5, 2. ],
       [5.5, 2.3, 4. , 1.3, 2. ],
       [6.5, 2.8, 4.6, 1.5, 2. ],
       [5.7, 2.8, 4.5, 1.3, 2. ],
       [6.3, 3.3, 4.7, 1.6, 2. ],
       [6.6, 2

In [44]:
# Si on effectue seulement le test :

iris[:,0]>5

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False, False, False,
        True,  True, False, False,  True,  True,  True, False, False,
        True, False, False,  True, False, False, False, False,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

### 1.2.3. Fancy indexing

Le but est simple : fonner un tableau d'indices entre corechets à notre ndarray poru sélectionner plusieurs éléments non consécutifs

In [46]:
notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10])
print(notre_tableau)
print("Notre nouveau tableau après fancy indexing :")
print(notre_tableau[np.array([[4,9,5],[1,8,3]])])

[ 1  2  3  4  5  6  7  8  9 10]
Notre nouveau tableau après fancy indexing :
[[ 5 10  6]
 [ 2  9  4]]


## 1.2. Accéder aux éléments par tranche (slicing)

### 1.3.1. Slicing sur un tableau NumpY à 1d

In [47]:
# Les trois premiers éléments
notre_tableau[:3]

array([1, 2, 3])

In [49]:
# Les derniers éléments à partir de l'index 5
notre_tableau[5:]

array([ 6,  7,  8,  9, 10])

In [53]:
# Du troisième au septième indice
notre_tableau[3:7]

array([4, 5, 6, 7])

In [56]:
# Avec un pas de 2 à partir de l'indice 1
notre_tableau[1::2]

array([ 2,  4,  6,  8, 10])

### 1.3.2. Slicing sur un tableau NumPy à 2D

In [57]:
# Ici on sélectionne les deux première lignes des 4 premières colonnes
iris[:2,:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [58]:
# Les dernières lignes à partir de l'index 145 et les dernières colonnes à partir de l'indice 2
iris[145:,2:]

array([[5.2, 2.3, 3. ],
       [5. , 1.9, 3. ],
       [5.2, 2. , 3. ],
       [5.4, 2.3, 3. ],
       [5.1, 1.8, 3. ]])

In [8]:
# Affiche toutes les colonnes de la ligne 0
iris[0,:]

array([5.1, 3.5, 1.4, 0.2, 1. ])

In [60]:
# Affiche toutes les lignes de la colonne 0
iris[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])