# 1. Les tableaux Numpy

## 1.1 Créer un ndarray

### 1.1.1. Créer un ndarray à partir de listes

In [3]:
import numpy as np

notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10])

print(notre_tableau)
type(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10]


numpy.ndarray

In [7]:
mon_array_bidimensionnel = np.array( [ [1,2,3],[4,5,6],[7,8,9] ] )
print(mon_array_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# pour sélectionner la valeur de la troisième colonne première ligne

print(mon_array_bidimensionnel[0][2])
print(mon_array_bidimensionnel[0,2])

# pour sélectionner la première ligne

print(mon_array_bidimensionnel[:,0])

# pour sélectionner la première colonne

print(mon_array_bidimensionnel[0,:])

3
3
[1 4 7]
[1 2 3]


### Il s'agit d'un tableau d'entiers, on ne peut pas changer une valeur par un string par exemple

In [14]:
mon_array_bidimensionnel[0,0]="texte"

ValueError: invalid literal for int() with base 10: 'texte'

In [17]:
# attribut dtype : type de données dans l'array

mon_array_bidimensionnel.dtype

dtype('int32')

In [18]:
mon_array_bidimensionnel = np.array([[1,2,3],[4,5,6]], dtype = float)
print(mon_array_bidimensionnel)
mon_array_bidimensionnel.dtype

[[1. 2. 3.]
 [4. 5. 6.]]


dtype('float64')

### 1.1.2. Créer un ndarray grâce à des fonctions NumPy

In [19]:
# np.zeros() permet de créer un ndarray dont l'ensemble des éléments correspondent à la valeur 0.mon_array_bidimensionnel

array_zeros = np.zeros((4,6))
print(array_zeros)

# on peut spécifier le type aussi

array_zeros = np.zeros((4,6), dtype = int)
print(array_zeros)

# Si on veut seulement des uns, on utilise la fonction ones

array_ones = np.ones((4,6), dtype = int)
print(array_ones)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [24]:
# np.random/random() permet de réer un ndarray dont les valeurs des éléments sont aléatoires entre 0 et 1

array_random = np.random.random((4,2))
print(array_random)

[[0.59920881 0.36915288]
 [0.53925824 0.67163294]
 [0.75536897 0.97031014]
 [0.53985    0.65839206]]


### Fichier iris.csv

In [29]:
# Charger les données d'un fichier txt ou csv

iris = np.genfromtxt("jeux_de_donnees/iris.csv", delimiter = ";", skip_header = True)
print(iris)
print(iris.dtype)
type(iris)

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

numpy.ndarray

In [31]:
# Sauvegarder les données dans un fichier txt ou csv

np.savetxt("jeux_de_donnees/iris_2.csv", iris, delimiter = ";")

## 1.2. Indexation

### 1.2.1. Indexation simple