# 1. Les tableaux Numpy

## 1.1 Créer un ndarray

### 1.1.1. Créer un ndarray à partir de listes

In [3]:
import numpy as np

notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10])

print(notre_tableau)
type(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10]


numpy.ndarray

In [3]:
mon_array_bidimensionnel = np.array( [ [1,2,3],[4,5,6],[7,8,9] ] )
print(mon_array_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# pour sélectionner la valeur de la troisième colonne première ligne

print(mon_array_bidimensionnel[0][2])
print(mon_array_bidimensionnel[0,2])

# pour sélectionner la première ligne

print(mon_array_bidimensionnel[:,0])

# pour sélectionner la première colonne

print(mon_array_bidimensionnel[0,:])

3
3
[1 4 7]
[1 2 3]


### Il s'agit d'un tableau d'entiers, on ne peut pas changer une valeur par un string par exemple

In [5]:
mon_array_bidimensionnel[0,0]="texte"

ValueError: invalid literal for int() with base 10: 'texte'

In [17]:
# attribut dtype : type de données dans l'array

mon_array_bidimensionnel.dtype

dtype('int32')

In [18]:
mon_array_bidimensionnel = np.array([[1,2,3],[4,5,6]], dtype = float)
print(mon_array_bidimensionnel)
mon_array_bidimensionnel.dtype

[[1. 2. 3.]
 [4. 5. 6.]]


dtype('float64')

### 1.1.2. Créer un ndarray grâce à des fonctions NumPy

In [19]:
# np.zeros() permet de créer un ndarray dont l'ensemble des éléments correspondent à la valeur 0.mon_array_bidimensionnel

array_zeros = np.zeros((4,6))
print(array_zeros)

# on peut spécifier le type aussi

array_zeros = np.zeros((4,6), dtype = int)
print(array_zeros)

# Si on veut seulement des uns, on utilise la fonction ones

array_ones = np.ones((4,6), dtype = int)
print(array_ones)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [24]:
# np.random/random() permet de réer un ndarray dont les valeurs des éléments sont aléatoires entre 0 et 1

array_random = np.random.random((4,2))
print(array_random)

[[0.59920881 0.36915288]
 [0.53925824 0.67163294]
 [0.75536897 0.97031014]
 [0.53985    0.65839206]]


### Fichier iris.csv

In [4]:
# Charger les données d'un fichier txt ou csv

iris = np.genfromtxt("jeux_de_donnees/iris.csv", delimiter = ";", skip_header = True)
print(iris)
print(iris.dtype)
type(iris)

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

numpy.ndarray

In [31]:
# Sauvegarder les données dans un fichier txt ou csv

np.savetxt("jeux_de_donnees/iris_2.csv", iris, delimiter = ";")

## 1.2. Indexation

### 1.2.1. Indexation simple

In [32]:
iris[2,1]

3.2

In [37]:
# Modifier la valeur à la troisième ligne, deuxième colonne

iris[2,1] = 4
iris[2,1]

4.0

### 1.2.2. Indexation booléenne

Pour sélectionner une portion de tableau on peut utiliser des masques booléens. == != < > <= >=

In [39]:
# On souhaite garder les valeurs supérieures à 2, peu importe la colonne

iris[iris>2] # On se retrouver avec un tableau unidimmensionnel

array([5.1, 3.5, 4.9, 3. , 4.7, 4. , 4.6, 3.1, 5. , 3.6, 5.4, 3.9, 4.6,
       3.4, 5. , 3.4, 4.4, 2.9, 4.9, 3.1, 5.4, 3.7, 4.8, 3.4, 4.8, 3. ,
       4.3, 3. , 5.8, 4. , 5.7, 4.4, 5.4, 3.9, 5.1, 3.5, 5.7, 3.8, 5.1,
       3.8, 5.4, 3.4, 5.1, 3.7, 4.6, 3.6, 5.1, 3.3, 4.8, 3.4, 5. , 3. ,
       5. , 3.4, 5.2, 3.5, 5.2, 3.4, 4.7, 3.2, 4.8, 3.1, 5.4, 3.4, 5.2,
       4.1, 5.5, 4.2, 4.9, 3.1, 5. , 3.2, 5.5, 3.5, 4.9, 3.6, 4.4, 3. ,
       5.1, 3.4, 5. , 3.5, 4.5, 2.3, 4.4, 3.2, 5. , 3.5, 5.1, 3.8, 4.8,
       3. , 5.1, 3.8, 4.6, 3.2, 5.3, 3.7, 5. , 3.3, 7. , 3.2, 4.7, 6.4,
       3.2, 4.5, 6.9, 3.1, 4.9, 5.5, 2.3, 4. , 6.5, 2.8, 4.6, 5.7, 2.8,
       4.5, 6.3, 3.3, 4.7, 4.9, 2.4, 3.3, 6.6, 2.9, 4.6, 5.2, 2.7, 3.9,
       5. , 3.5, 5.9, 3. , 4.2, 6. , 2.2, 4. , 6.1, 2.9, 4.7, 5.6, 2.9,
       3.6, 6.7, 3.1, 4.4, 5.6, 3. , 4.5, 5.8, 2.7, 4.1, 6.2, 2.2, 4.5,
       5.6, 2.5, 3.9, 5.9, 3.2, 4.8, 6.1, 2.8, 4. , 6.3, 2.5, 4.9, 6.1,
       2.8, 4.7, 6.4, 2.9, 4.3, 6.6, 3. , 4.4, 6.8, 2.8, 4.8, 6.

In [40]:
iris[iris>2].shape[0] # Nombre d'éléments supérieurs à 0

472

In [41]:
# L'expression booléenne qui suit génère un nouveau tableau, de même dimension que le tableau iris, mais qui contient uniquement des bool

iris>2

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, Fal

In [43]:
# Pour appliquer une condition sur une colonne particulère du tableau, il faut sélectionner en écrivant le masque booléen comme ceci :

iris[iris[:,0]>5] # On conserve la ligne si la première colonne est >5

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4.2, 1.4, 0.2, 1. ],
       [5.5, 3.5, 1.3, 0.2, 1. ],
       [5.1, 3.4, 1.5, 0.2, 1. ],
       [5.1, 3.8, 1.9, 0.4, 1. ],
       [5.1, 3.8, 1.6, 0.2, 1. ],
       [5.3, 3.7, 1.5, 0.2, 1. ],
       [7. , 3.2, 4.7, 1.4, 2. ],
       [6.4, 3.2, 4.5, 1.5, 2. ],
       [6.9, 3.1, 4.9, 1.5, 2. ],
       [5.5, 2.3, 4. , 1.3, 2. ],
       [6.5, 2.8, 4.6, 1.5, 2. ],
       [5.7, 2.8, 4.5, 1.3, 2. ],
       [6.3, 3.3, 4.7, 1.6, 2. ],
       [6.6, 2

In [44]:
# Si on effectue seulement le test :

iris[:,0]>5

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False, False, False,
        True,  True, False, False,  True,  True,  True, False, False,
        True, False, False,  True, False, False, False, False,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

### 1.2.3. Fancy indexing

Le but est simple : fonner un tableau d'indices entre corechets à notre ndarray poru sélectionner plusieurs éléments non consécutifs

In [46]:
notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10])
print(notre_tableau)
print("Notre nouveau tableau après fancy indexing :")
print(notre_tableau[np.array([[4,9,5],[1,8,3]])])

[ 1  2  3  4  5  6  7  8  9 10]
Notre nouveau tableau après fancy indexing :
[[ 5 10  6]
 [ 2  9  4]]


## 1.2. Accéder aux éléments par tranche (slicing)

### 1.3.1. Slicing sur un tableau NumpY à 1d

In [47]:
# Les trois premiers éléments
notre_tableau[:3]

array([1, 2, 3])

In [49]:
# Les derniers éléments à partir de l'index 5
notre_tableau[5:]

array([ 6,  7,  8,  9, 10])

In [53]:
# Du troisième au septième indice
notre_tableau[3:7]

array([4, 5, 6, 7])

In [56]:
# Avec un pas de 2 à partir de l'indice 1
notre_tableau[1::2]

array([ 2,  4,  6,  8, 10])

### 1.3.2. Slicing sur un tableau NumPy à 2D

In [57]:
# Ici on sélectionne les deux première lignes des 4 premières colonnes
iris[:2,:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [58]:
# Les dernières lignes à partir de l'index 145 et les dernières colonnes à partir de l'indice 2
iris[145:,2:]

array([[5.2, 2.3, 3. ],
       [5. , 1.9, 3. ],
       [5.2, 2. , 3. ],
       [5.4, 2.3, 3. ],
       [5.1, 1.8, 3. ]])

In [8]:
# Affiche toutes les colonnes de la ligne 0
iris[0,:]

array([5.1, 3.5, 1.4, 0.2, 1. ])

In [60]:
# Affiche toutes les lignes de la colonne 0
iris[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [5]:
 iris[-1,:]

array([5.9, 3. , 5.1, 1.8, 3. ])

In [6]:
sous_tableau = notre_tableau[:5]
sous_tableau

array([1, 2, 3, 4, 5])

In [7]:
sous_tableau[0] = 10
sous_tableau

array([10,  2,  3,  4,  5])

In [8]:
 notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
notre_tableau= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

sous_tableau = notre_tableau[:5].copy()
sous_tableau[0] = 10
print(sous_tableau)
print(notre_tableau)

[10  2  3  4  5]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [10]:
mon_tableau = np.array([[10,11,12],[13,14,15],[16,17,18]])
mon_tableau

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [11]:
np.add(mon_tableau,10)

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [12]:
# Multiplier
m = np.multiply(mon_tableau,20)
print(m)
print(mon_tableau)

[[200 220 240]
 [260 280 300]
 [320 340 360]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [13]:
 mon_tableau_2 = np.array([10,20,30])
print(mon_tableau_2)
print(mon_tableau)

[10 20 30]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [15]:
# Soustraire
np.subtract(mon_tableau,mon_tableau_2)

array([[  0,  -9, -18],
       [  3,  -6, -15],
       [  6,  -3, -12]])

In [16]:
mon_tableau_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mon_tableau_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.multiply(mon_tableau,mon_tableau_3)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [19]:
print("Somme sur les colonnes :")
print(np.sum(iris, axis=0))

print("Somme par ligne: ")
print(np.sum(iris, axis=1))

Somme sur les colonnes :
[876.5 458.6 563.7 179.9 300. ]
Somme par ligne: 
[11.2 10.5 10.4 10.4 11.2 12.4 10.7 11.1  9.9 10.6 11.8 11.  10.3  9.5
 12.2 13.  12.  11.3 12.5 11.7 11.7 11.7 10.4 11.6 11.3 10.8 11.4 11.4
 11.2 10.7 10.7 11.7 11.9 12.3 10.7 10.6 11.5 11.   9.9 11.2 11.1  9.4
 10.1 11.7 12.2 10.5 11.7 10.4 11.7 10.9 18.3 17.6 18.4 15.1 17.4 16.3
 17.9 13.6 17.4 15.2 13.5 16.6 15.2 17.1 15.4 17.6 16.6 15.6 16.4 15.1
 17.7 16.2 17.2 16.8 16.9 17.4 17.8 18.4 16.9 14.8 14.8 14.6 15.6 17.4
 16.4 17.5 18.  16.3 16.  15.3 15.7 17.1 15.6 13.6 15.8 16.1 16.1 16.7
 13.7 15.9 21.1 18.5 21.1 19.6 20.5 22.3 16.6 21.3 19.8 22.4 19.8 19.3
 20.4 18.2 19.1 20.2 19.8 23.4 22.5 17.7 21.1 18.3 22.2 18.7 20.8 21.2
 18.6 18.8 19.9 20.6 21.2 23.1 20.  18.7 18.7 22.1 20.7 19.8 18.6 20.5
 20.8 20.4 18.5 21.2 21.2 20.2 18.7 19.7 20.3 18.8]


In [20]:
# Moyenne et ecartype
print(np.mean(iris, axis=0))
print(np.std(iris, axis=0))

[5.84333333 3.05733333 3.758      1.19933333 2.        ]
[0.82530129 0.43441097 1.75940407 0.75969263 0.81649658]


In [23]:
for i in range(3):

    print("\nMoyenne et écartype pour le type",i+1,":")
    moyenne = np.mean(iris[iris[:,4] == i+1], axis=0)
    print(moyenne)
    std = np.std(iris[iris[:,4] == i+1], axis=0)
    print(std)



Moyenne et écartype pour le type 1 :
[5.006 3.428 1.462 0.246 1.   ]
[0.34894699 0.37525458 0.17191859 0.10432641 0.        ]

Moyenne et écartype pour le type 2 :
[5.936 2.77  4.26  1.326 2.   ]
[0.51098337 0.31064449 0.46518813 0.19576517 0.        ]

Moyenne et écartype pour le type 3 :
[6.588 2.974 5.552 2.026 3.   ]
[0.62948868 0.31925538 0.54634787 0.27188968 0.        ]
