In [3]:
import pandas as pd
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [6]:
iris = pd.read_csv("donnees/iris.csv", delimiter=";", encoding="latin-1")
iris

Longueur des sépales  Largeur des sépales  Longueur des pétales  \
0                     5.1                  3.5                   1.4   
1                     4.9                  3.0                   1.4   
2                     4.7                  3.2                   1.3   
3                     4.6                  3.1                   1.5   
4                     5.0                  3.6                   1.4   
..                    ...                  ...                   ...   
145                   6.7                  3.0                   5.2   
146                   6.3                  2.5                   5.0   
147                   6.5                  3.0                   5.2   
148                   6.2                  3.4                   5.4   
149                   5.9                  3.0                   5.1   

     Largeur des pétales  Espèce  
0                    0.2       1  
1                    0.2       1  
2                    0.2       1  
3                    0.2       1  
4                    0.2       1  
..                   ...     ...  
145                  2.3       3  
146                  1.9       3  
147                  2.0       3  
148                  2.3       3  
149                  1.8       3  

[150 rows x 5 columns]

In [7]:
iris2 = iris[iris['Espèce']!=3]
iris2

Longueur des sépales  Largeur des sépales  Longueur des pétales  \
0                    5.1                  3.5                   1.4   
1                    4.9                  3.0                   1.4   
2                    4.7                  3.2                   1.3   
3                    4.6                  3.1                   1.5   
4                    5.0                  3.6                   1.4   
..                   ...                  ...                   ...   
95                   5.7                  3.0                   4.2   
96                   5.7                  2.9                   4.2   
97                   6.2                  2.9                   4.3   
98                   5.1                  2.5                   3.0   
99                   5.7                  2.8                   4.1   

    Largeur des pétales  Espèce  
0                   0.2       1  
1                   0.2       1  
2                   0.2       1  
3                   0.2       1  
4                   0.2       1  
..                  ...     ...  
95                  1.2       2  
96                  1.3       2  
97                  1.3       2  
98                  1.1       2  
99                  1.3       2  

[100 rows x 5 columns]

In [8]:
iris2.describe()

Longueur des sépales  Largeur des sépales  Longueur des pétales  \
count            100.000000           100.000000            100.000000   
mean               5.471000             3.099000              2.861000   
std                0.641698             0.478739              1.449549   
min                4.300000             2.000000              1.000000   
25%                5.000000             2.800000              1.500000   
50%                5.400000             3.050000              2.450000   
75%                5.900000             3.400000              4.325000   
max                7.000000             4.400000              5.100000   

       Largeur des pétales      Espèce  
count           100.000000  100.000000  
mean              0.786000    1.500000  
std               0.565153    0.502519  
min               0.100000    1.000000  
25%               0.200000    1.000000  
50%               0.800000    1.500000  
75%               1.300000    2.000000  
max               1.800000    2.000000

In [9]:
import numpy as np

iris2["Longueur_sépales_disc"] = pd.cut(iris2["Longueur des sépales"],
                               bins=5,
                               labels=["class1", "class2", "class3", "class4", "class5"])


<ipython-input-9-7998dbacbe33>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iris2["Longueur_sépales_disc"] = pd.cut(iris2["Longueur des sépales"],


In [10]:
iris2

Longueur des sépales  Largeur des sépales  Longueur des pétales  \
0                    5.1                  3.5                   1.4   
1                    4.9                  3.0                   1.4   
2                    4.7                  3.2                   1.3   
3                    4.6                  3.1                   1.5   
4                    5.0                  3.6                   1.4   
..                   ...                  ...                   ...   
95                   5.7                  3.0                   4.2   
96                   5.7                  2.9                   4.2   
97                   6.2                  2.9                   4.3   
98                   5.1                  2.5                   3.0   
99                   5.7                  2.8                   4.1   

    Largeur des pétales  Espèce Longueur_sépales_disc  
0                   0.2       1                class2  
1                   0.2       1                class2  
2                   0.2       1                class1  
3                   0.2       1                class1  
4                   0.2       1                class2  
..                  ...     ...                   ...  
95                  1.2       2                class3  
96                  1.3       2                class3  
97                  1.3       2                class4  
98                  1.1       2                class2  
99                  1.3       2                class3  

[100 rows x 6 columns]

### Test du chi2

Ce test permet de vérifier l'absence de lien statistique entre deux variables X et Y.

Les deux sont dites indépendantes lorsqu'il n'existe aucun lien statistique entre elles, dit autrement, la connaissance de X ne permet en aucune manière de se prononcer sur Y.

L'hypothèse nulle (H0) de ce test est la suivante : les deux variables X et Y sont indépendantes.

En termes de valeur p, l'hypothèse nulle est généralement rejetée lorsque p ≤ 0,05. 

In [11]:
M1 = np.unique(iris2['Espèce'], return_counts=True)
M2 = np.unique(iris2['Longueur_sépales_disc'], return_counts=True)
M2

(array(['class1', 'class2', 'class3', 'class4', 'class5'], dtype=object),
 array([16, 29, 31, 15,  9], dtype=int64))

In [12]:
cont = iris2[["Espèce", "Longueur_sépales_disc"]].pivot_table(
    index="Espèce", columns="Longueur_sépales_disc", aggfunc=len).fillna(0).copy().astype(int)

cont

Longueur_sépales_disc  class1  class2  class3  class4  class5
Espèce                                                       
1                          16      24      10       0       0
2                           0       5      21      15       9

In [13]:
from scipy.stats import chi2_contingency
st_chi2, st_p, st_dof, st_exp = chi2_contingency(cont)
st_p

1.6921892453303934e-11

In [14]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1,
                               test_size=0.2, random_state=42)

for train_index, test_index in split.split(iris2, iris2["Espèce"]):
    strat_train_set = iris2.loc[train_index]
    strat_test_set = iris2.loc[test_index]

X_train = np.c_[strat_train_set[["Longueur des sépales", "Largeur des sépales",
                                "Longueur des pétales", "Largeur des pétales"]]]
y_train = np.array(strat_train_set["Espèce"])

X_test = np.c_[strat_test_set[["Longueur des sépales", "Largeur des sépales",
                                "Longueur des pétales", "Largeur des pétales"]]]
y_test = np.array(strat_test_set["Espèce"])

In [15]:
model = make_pipeline(StandardScaler(),
                     SGDClassifier(max_iter=1000, loss='log'))
model.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdclassifier', SGDClassifier(loss='log'))])

In [16]:
model.predict(X_test)

array([2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 2],
      dtype=int64)

In [17]:
model.predict_proba(X_test) 

array([[6.06612025e-03, 9.93933880e-01],
       [5.46852817e-07, 9.99999453e-01],
       [2.47499609e-05, 9.99975250e-01],
       [1.14291240e-04, 9.99885709e-01],
       [9.99999496e-01, 5.03651891e-07],
       [9.99999991e-01, 8.97388399e-09],
       [9.99997909e-01, 2.09068325e-06],
       [4.06688967e-05, 9.99959331e-01],
       [9.99999671e-01, 3.28780712e-07],
       [9.99999990e-01, 1.03111357e-08],
       [9.99999584e-01, 4.15937936e-07],
       [2.40958162e-05, 9.99975904e-01],
       [9.99999100e-01, 9.00120502e-07],
       [9.99997762e-01, 2.23819776e-06],
       [9.99999901e-01, 9.94152546e-08],
       [2.09555953e-03, 9.97904440e-01],
       [2.63813532e-04, 9.99736186e-01],
       [9.99999391e-01, 6.09087450e-07],
       [8.51531382e-05, 9.99914847e-01],
       [2.02383505e-04, 9.99797616e-01]])

In [18]:
model.classes_

array([1, 2], dtype=int64)

Un classifieur construit une frontière entre deux classes, la distance d’un point à la frontière constitue une information importante. Plus elle est grande, plus le modèle est confiant. Cette distance est souvent appelée score.

In [19]:
model.decision_function(X_test)

array([  5.09895145,  14.4190856 ,  10.6066619 ,   9.07664633,
       -14.50138   , -18.52894725, -13.07801754,  10.1100063 ,
       -14.92787451, -18.39004138, -14.69272936,  10.63344824,
       -13.92073629, -13.00983735, -16.12396017,   6.16583692,
         8.24000417, -14.31130337,   9.37097414,   8.50514372])

#### Matrice de confusion

In [20]:
from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y_test, model.predict(X_test))
conf

array([[10,  0],
       [ 0, 10]], dtype=int64)

#### Valeur de la courbe roc

In [22]:
from sklearn.metrics import roc_curve, auc

fpr, tpr, thresholds = roc_curve(y_test, model.decision_function(X_test), pos_label=2)

print(fpr)

print(tpr)

print(thresholds)

[0. 0. 0. 1.]
[0.  0.1 1.  1. ]
[ 15.4190856   14.4190856    5.09895145 -18.52894725]


- fpr désigne le False Positive Rate autrement dit le taux de faux positive, C’est l’erreur de classification. 
- tpr désigne le nombre de True Positive Rate.
- True et False ne sont pas vrai ou faux mais le nom de deux classes.

#### L'aire sous la courbe

In [23]:
auc = auc(fpr, tpr)
auc

1.0

3